//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedInvoices.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facture()
        {
            this.Produit_Facture = new HashSet<Produit_Facture>();
        }
    
        public int IdFacture { get; set; }
        public string ReferenceFacture { get; set; }
        public System.DateTime DateCreationFacture { get; set; }
        public int RemiseFacture { get; set; }
        public float Tva { get; set; }
        public float MontantHtFacture { get; set; }
        public float MontantTtcFacture { get; set; }
        public int IdEtat { get; set; }
        public int IdClient { get; set; }
        public int IdStructure { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Etat Etat { get; set; }
        public virtual Structure Structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit_Facture> Produit_Facture { get; set; }
    }
}
