//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedInvoices.Service.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Produit_Facture = new HashSet<Produit_Facture>();
        }
    
        public int IdProduit { get; set; }
        public string ReferenceProduit { get; set; }
        public string IntituleProduit { get; set; }
        public string DescriptionProduit { get; set; }
        public int PrixUnitaireProduit { get; set; }
        public int IdCategorie { get; set; }
        public int IdStructure { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit_Facture> Produit_Facture { get; set; }
        public virtual Structure Structure { get; set; }
    }
}
